### ISSUE TITLE
Minor language-setting issues

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-Teams-NG#15]
I noticed two issues regarding the supported languages for the teams-module:

1) The default language for an invitation mail is always set to 'English', which should at least be configurable or follow the current user's language.

![afbeelding](https://user-images.githubusercontent.com/841045/83747190-924fdc80-a660-11ea-89b2-18d20ccf24d3.png)

2) I have removed 'pt' from the supported languages, but it still shows in the drop-down when sending an invitation mail.

![afbeelding](https://user-images.githubusercontent.com/841045/83747073-5e74b700-a660-11ea-8cf5-36309dcb0deb.png)

**Comment by oharsta** [comment]
Fixed in https://github.com/OpenConext/OpenConext-Teams-NG/commit/93aa585dd1d60b7131199596f3e77ae4d5e8f296 and https://github.com/OpenConext/OpenConext-Teams-NG/commit/6941b39870a3d1ab70543057e607834901b5599e. Uploaded new 8.3.8-SNAPSHOT release to https://build.openconext.org/repository/public/snapshots

**Comment by oharsta** [comment]
Uploaded and tagged release 8.3.8
